Rails.application.config.assets.precompile += %w( bootstrap.min.css )
Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( set.css)
Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( animate.css )
Rails.application.config.assets.precompile += %w( blueimp-gallery.min.css )


Rails.application.config.assets.precompile += %w( jquery.blueimp-gallery.min.js )
Rails.application.config.assets.precompile += %w( jquery.js )
Rails.application.config.assets.precompile += %w( bootstrap.js )
Rails.application.config.assets.precompile += %w( respond.js )
Rails.application.config.assets.precompile += %w( script.js )
Rails.application.config.assets.precompile += %w( touchSwipe.min.js )
Rails.application.config.assets.precompile += %w( wow.min.js )
